data_cfg:
  dataset_name: CASIA-B
  dataset_root: /home/sp/datasets/CASIA_B/Silhouette_pkl
  dataset_partition: ./datasets/CASIA-B/CASIA-B.json
  num_workers: 12
  remove_no_gallery: false # Remove probe if no gallery for it
  test_dataset_name: CASIA-B

evaluator_cfg:
  enable_float16: true
  restore_ckpt_strict: true
  restore_hint: 0
  save_name: FFormer_E2E_Sopt_NO_BASE
  eval_func: evaluate_gait_rec
  sampler:
    batch_shuffle: false
    batch_size: 2
    sample_type: all_ordered
    frames_all_limit: 720
  transform:
    - type: BaseSilCuttingTransform
    - type: BaseSilCuttingTransform

loss_cfg:
  - loss_term_weight: 1
    type: AdversarialLoss
    log_prefix: adv
  - loss_term_weight: 1
    type: GanLoss
    log_prefix: gan
    imgloss_type: 'L1'
    adversarial_weight: 1
    img_weight: 100
  - loss_term_weight: 1
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 1.0
    scale: 16
    type: CrossEntropyLoss
    log_prefix: softmax
    log_accuracy: true

model_cfg:
  model: FFormer_E2E_Sopt
  Gait:
    Backbone:
      mode: p3d
      in_channels: 1
      layers:
        - 1
        - 1
        - 1
        - 1
      channels: 
        - 64
        - 128 
        - 256
        - 512
    SeparateBNNecks:
      class_num: 74
  Gen:
    channel: 256  #normal encoder
    # channel: 512 # slim encoder
    hidden: 512
    stack_num: 2
    num_head: 4
    dropout: 0.
    kernel_size:
      - 3
      - 3
    padding:
      - 3
      - 3
    stride:
      - 3
      - 3
    output_size:
      - 16
      - 11
  Dis:
    input_c: 1
    hidden_size: 32
    use_sigmoid: True
  lr_D: 0.0001
  lr_gait: 0.0001

optimizer_cfg:
  lr: 0.0002
  betas:
    - 0
    - 0.99
  solver: Adam
  weight_decay: 0.0005

scheduler_cfg:
  gamma: 0.1
  milestones: # Learning Rate Reduction at each milestones
    - 35000
    - 50000
  scheduler: MultiStepLR

trainer_cfg:
  enable_float16: true # half_percesion float for memory reduction and speedup
  with_test: true
  log_iter: 500
  restore_ckpt_strict: false
  restore_hint: 0
  optimizer_reset: true
  scheduler_reset: true
  sync_BN: true
  save_iter: 10000
  save_name: FFormer_E2E_Sopt_NO_BASE
  total_iter: 60000
  sampler:
    batch_shuffle: false
    batch_size:
      - 8 # TripletSampler, batch_size[0] indicates Number of Identity
      - 4 #                 batch_size[1] indicates Samples sequqnce for each Identity
    # frames_num_fixed: 30
    # frames_skip_num: 0
    frames_num_fixed: 30 # fixed frames number for training
    frames_num_max: 40 # max frames number for unfixed training
    frames_num_min: 20 # min frames number for unfixed traing
    sample_type: fixed_ordered
    frames_skip_num: 0
    type: TripletSampler
  transform:
    - type: BaseSilCuttingTransform
    - type: BaseSilCuttingTransform