data_cfg:
  dataset_name: CASIA-B
  dataset_root: /home/sp/datasets/CASIA_B/silhouettes_seg_cut_pkl
  num_workers: 12
  remove_no_gallery: false
  test_dataset_name: CASIA-B

evaluator_cfg:
  enable_float16: true
  restore_ckpt_strict: true
  restore_hint: 0
  save_name: Phase_Rec
  eval_func: evaluate_gait_rec
  sampler:
    batch_size: 32
    frames_num_fixed: 30 # fixed frames number for training
    sample_type: fixed_ordered
    frames_skip_num: 0
    type: InferenceSampler
  transform:
    - type: BaseSilTransform
    - type: BaseSilTransform

loss_cfg:
  - loss_term_weight: 1
    type: AdversarialLoss
    log_prefix: adv
  - loss_term_weight: 1
    type: GanLoss
    log_prefix: gan
    imgloss_type: 'L1'
    adversarial_weight: 1
    img_weight: 100
  - loss_term_weight: 1
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet

model_cfg:
  model: SimVP_Rec
  GaitSet:
    in_channels:
      - 1
      - 32
      - 64
      - 128
    SeparateFCs:
      in_channels: 128
      out_channels: 256
      parts_num: 62
    bin_num:
      - 16
      - 8
      - 4
      - 2
      - 1
  shape_in: 
    - 30
    - 1
    - 64
    - 64
  hid_S: 16
  hid_T: 256
  N_S: 4
  N_T: 4
  incep_ker:
    - 3
    - 5
    - 7
    - 11
  groups: 4
  Dis:
    input_c: 1
    hidden_size: 32
    use_sigmoid: True
  gait_lr: 0.001

optimizer_cfg:
  lr: 0.003
  betas:
    - 0
    - 0.99
  solver: Adam
  weight_decay: 0.0005

# optimizer_cfg:
#   lr: 0.1
#   momentum: 0.9
#   solver: SGD
#   weight_decay: 0.0005

scheduler_cfg:
  gamma: 0.1
  milestones: # Learning Rate Reduction at each milestones
  # adam
    - 25000
    - 50000
# sgd
    # - 20000
    # - 40000
    # - 50000
  scheduler: MultiStepLR
trainer_cfg:
  enable_float16: true # half_percesion float for memory reduction and speedup
  with_test: true
  log_iter: 100
  restore_ckpt_strict: true
  restore_hint: 0
  optimizer_reset: true
  scheduler_reset: true
  sync_BN: true
  save_iter: 10000
  save_name: GAIT_REC_2_phase
  total_iter: 80000
  sampler:
    batch_shuffle: false
    batch_size:
      - 16 # TripletSampler, batch_size[0] indicates Number of Identity
      - 4 #                 batch_size[1] indicates Samples sequqnce for each Identity
    # frames_num_fixed: 30
    # frames_skip_num: 0
    frames_num_fixed: 30 # fixed frames number for training
    frames_num_max: 40 # max frames number for unfixed training
    frames_num_min: 20 # min frames number for unfixed traing
    sample_type: fixed_ordered
    frames_skip_num: 0
    type: TripletSampler
  transform:
    - type: BaseSilTransform
    - type: BaseSilTransform

