data_cfg:
  dataset_name: CASIA-B
  dataset_root: /home/sp/datasets/CASIA_B/Silhouette_pkl
  dataset_partition: ./datasets/CASIA-B/CASIA-B.json
  num_workers: 12
  remove_no_gallery: false # Remove probe if no gallery for it
  test_dataset_name: CASIA-B


evaluator_cfg:
  enable_float16: true
  restore_ckpt_strict: true
  restore_hint: 80000
  save_name: SwinGait3D_B1111_C2
  sampler:
    batch_shuffle: false
    batch_size: 2
    sample_type: all_ordered # all indicates whole sequence used to test, while ordered means input sequence by its natural order; Other options:   fixed_unordered
    frames_all_limit: 720 # limit the number of sampled frames to prevent out of memory
  metric: euc # cos
  transform:
    - type: BaseSilCuttingTransform
    - type: BaseSilCuttingTransform

loss_cfg:
  - loss_term_weight: 1
    type: AdversarialLoss
    log_prefix: adv
  - loss_term_weight: 1
    type: GanLoss
    log_prefix: gan
    imgloss_type: 'L1'
    adversarial_weight: 1
    img_weight: 100
  - loss_term_weight: 1
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 1.0
    scale: 16
    type: CrossEntropyLoss
    log_prefix: softmax
    log_accuracy: true
    

model_cfg:
  model: FFormerSwinGait
  Backbone:
    mode: p3d
    in_channels: 1
    layers:
      - 1
      - 1
      - 1
      - 1
    channels:
      - 64
      - 128
  bin_num: 
    - 15
  SeparateBNNecks:
    in_channels: 128
    class_num: 74
    parts_num: 16
  ss_channel: 256
  hidden: 256
  stack_num: 2
  num_head: 4
  dropout: 0.
  kernel_size:
    - 3
    - 3
  padding:
    - 3
    - 3
  stride:
    - 3
    - 3
  output_size:
    - 16
    - 11
  Dis:
    input_c: 1
    hidden_size: 32
    use_sigmoid: True
  lr_D: 0.0001

optimizer_cfg:
  lr: 0.0003
  solver: AdamW
  weight_decay: 0.02

scheduler_cfg:
  gamma: 0.1
  milestones: # Learning Rate Reduction at each milestones
    - 100000000
  scheduler: MultiStepLR

trainer_cfg:
  enable_float16: true # half_percesion float for memory reduction and speedup
  fix_BN: false
  log_iter: 500
  with_test: True
  optimizer_reset: True
  restore_ckpt_strict: false
  restore_hint: 0
  save_iter: 20000
  save_name: SwinGait3D_B1111_C2
  sync_BN: true
  T_max_iter: 60000
  total_iter: 80000
  sampler:
    batch_shuffle: true
    batch_size:
      - 2 # TripletSampler, batch_size[0] indicates Number of Identity
      - 2 #                 batch_size[1] indicates Samples sequqnce for each Identity
    frames_num_fixed: 30 # fixed frames number for training
    frames_skip_num: 0
    sample_type: fixed_ordered # fixed control input frames number, unordered for controlling order of input tensor; Other options: unfixed_ordered or all_ordered
    type: TripletSampler
  transform:
    # - type: Compose
    #   trf_cfg:
    #     - type: RandomPerspective
    #       prob: 0.2
    #     - type: BaseSilCuttingTransform
    #     - type: RandomHorizontalFlip
    #       prob: 0.2
    #     - type: RandomRotate
    #       prob: 0.2
    - type: BaseSilCuttingTransform
    - type: BaseSilCuttingTransform



