data_cfg:
  dataset_name: OUMVLP
  dataset_root: /home/sp/datasets/OUMVLP/OUMVLP_Silhouette_pkl
  dataset_partition: ./datasets/OUMVLP/OUMVLP.json
  num_workers: 8
  remove_no_gallery: false # Remove probe if no gallery for it
  test_dataset_name: OUMVLP

evaluator_cfg:
  enable_float16: true
  restore_ckpt_strict: true
  restore_hint: 0
  save_name: Origin_FFormer_Rec_Encoder_Concat_8_8
  metric: euc # cos
  sampler:
    batch_shuffle: false
    batch_size: 2
    sample_type: all_ordered
    frames_all_limit: 720
  transform:
    - type: BaseSilCuttingTransform

loss_cfg:
  - loss_term_weight: 1
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 1.0
    scale: 16
    type: CrossEntropyLoss
    log_prefix: softmax
    log_accuracy: true

model_cfg:
  model: OriginFormerGaitConcat
  SeparateBNNecks:
    class_num: 5153
  ss_channel: 512  #normal encoder
  hidden: 512
  stack_num: 2
  num_head: 2
  dropout: 0.
  kernel_size:
    - 3
    - 3
  padding:
    - 3
    - 3
  stride:
    - 3
    - 3
  output_size:
    - 16
    - 11

optimizer_cfg:
  lr: 0.0002
  betas:
    - 0.9
    - 0.99
  solver: AdamW
  weight_decay: 0.0005

# optimizer_cfg:
#   lr: 0.1
#   momentum: 0.9
#   solver: SGD
#   weight_decay: 0.0005

scheduler_cfg:
  gamma: 0.1
  milestones: # Learning Rate Reduction at each milestones
    - 100000
    - 150000
  scheduler: MultiStepLR

trainer_cfg:
  enable_float16: true # half_percesion float for memory reduction and speedup
  with_test: true
  log_iter: 1000
  restore_ckpt_strict: false
  restore_hint: 0
  optimizer_reset: false
  scheduler_reset: false
  sync_BN: true
  save_iter: 10000
  save_name: Origin_FFormer_Rec_Encoder_Concat_8_8
  total_iter: 210000
  sampler:
    batch_shuffle: false
    batch_size:
      - 16 # TripletSampler, batch_size[0] indicates Number of Identity
      - 8 #                 batch_size[1] indicates Samples sequqnce for each Identity
    frames_num_fixed: 30 # fixed frames number for training
    sample_type: fixed_ordered
    frames_skip_num: 0
    type: TripletSampler
  transform:
    - type: Compose
      trf_cfg:
        - type: RandomPerspective
          prob: 0.2
        - type: BaseSilCuttingTransform
        - type: RandomHorizontalFlip
          prob: 0.2
        - type: RandomRotate
          prob: 0.2