data_cfg:
  dataset_name: CASIA-B
  dataset_root: /home/sp/sp/dataset/CASIA-B/Silhouette_pkl
  dataset_partition: ./datasets/CASIA-B/CASIA-B.json
  num_workers: 12
  remove_no_gallery: false # Remove probe if no gallery for it
  test_dataset_name: CASIA-B

evaluator_cfg:
  enable_float16: false
  restore_ckpt_strict: true
  restore_hint: 70000
  save_name: LagrangeGait_CASIA_B
  # eval_func: identification
  sampler:
    batch_size: 1
    sample_type: all_ordered
    frames_all_limit: 720 # limit the number of sampled frames to prevent out of memory
  metric: euc # cos
  transform:
    - type: BaseSilCuttingTransform

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weights: 1.0
    scale: 1
    type: CrossEntropyLoss
    log_accuracy: true
    label_smooth: false
    log_prefix: softmax
#  - loss_term_weight: 0.2
#    scale: 1
#    type: CrossEntropyLoss
#    log_accuracy: true
#    label_smooth: false
#    log_prefix: view_softmax

#loss_cfg:
#  - loss_term_weights: 1.0
#    margin: 0.2
#    type: TripletLoss
#    log_prefix: triplet
#  - loss_term_weights: 1.0
#    scale: 1
#    type: CrossEntropyLoss
#    log_accuracy: true
#    label_smooth: true
#    log_prefix: softmax
#  - loss_term_weights: 0.2
#    scale: 1
#    type: CrossEntropyLoss
#    log_accuracy: true
#    label_smooth: false
#    log_prefix: view_softmax


model_cfg:
  model: LagrangeGait_New
  channels: [32, 64, 128, 256]
  view_nums: 11
  radius: 3
  class_num: 74

optimizer_cfg:
  lr: 1.0e-4
  solver: Adam
  weight_decay: 5.0e-4

scheduler_cfg:
  gamma: 0.1
  milestones:
    - 70000
  scheduler: MultiStepLR

trainer_cfg:
  enable_float16: true
  with_test: true
  log_iter: 100
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 1000
  save_name: LagrangeGait_CASIA_B
  sync_BN: true
  total_iter: 70000
  fix_BN: false
  transform:
    - type: BaseSilCuttingTransform
      img_w: 64
  sampler:
    batch_shuffle: true
    batch_size:
      - 8
      - 8
    frames_num_fixed: 30
    frames_skip_num: 0
    sample_type: fixed_ordered
    type: TripletSampler
